version: '3'
services:
  react-app:
    build:
      context: ./
    image: ${SOCKET_IMAGE}
    ports:
      - "80:80"
    depends_on:
      - socket-server

  socket-server:
    build:
      context: ./Server
    image: ${REACT_IMAGE}
    ports:
      - "3001:3001"