version: '3'
services:
  react-app:
    build:
      context: ./
    image: docker.io/ducthuanle/cc_react-app:latest
    ports:
      - "80:80"
    depends_on:
      - socket-server

  socket-server:
    build:
      context: ./Server
    image: docker.io/ducthuanle/cc_socket-server:latest
    ports:
      - "3001:3001"


