name: Docker Image CI + DockerHub push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push Docker Compose setup
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

        # Build and tag the Docker Compose setup
        #docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml build -t docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY_REACT_APP }}:latest

        # Push the Docker Compose setup
        docker-compose -f docker-compose.yml push
